lab7/myimgur/app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:image_id>', views.detail, name="detail")
]

lab7/myimgur/myimgur/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('images/', include('app.urls')),
]

lab7/myimgur/app/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    url = models.CharField(max_length=256, blank=False)
    title = models.CharField(max_length=128, blank=False)
    pub_date = models.DateTimeField('Published at')
    def __str__(self):
        return f"{self.id}-{self.title[:20]}"
    
class Comment(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    pub_date = models.DateTimeField('Published at')
    nick = models.CharField(max_length=128, blank=False, default='anon')
    def __str__(self):
        return f"{self.id}-{self.image.title[:15]}-{self.text}"
    

lab7/myimgur/app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Image

# Create your views here.
def home(request):
    context = {}
    return render(request, 'app/home.html', context)

def index(request):
    images = Image.objects.all()
    context = {
        'image_list': images
    }
    return render(request, 'app/index.html', context)

def detail(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    context = {
        'image': image
    }
    return render(request, 'app/detail.html', context)

lab7/myimgur/app/templates/app/detail.html
<html>
    <head>
        <title>Naš imgur</title>
    </head>
    <body>
        <p>
            <a href="{% url 'home_path' %}">HOME</a>
        </p>
        <h1>{{ image.title }}</h1>
        <div>
            <p>Objavljeno: {{ image.pub_date }}</p>
            <img src="{{ image.url }}" style="width:800px;">
        </div>
    

        
    </body>
</html>

lab7/myimgur/app/templates/app/home.html
<html>
    <head>
        <title>Naš imgur</title>
    </head>
    <body>
        <h1>MyImgur</h1>
        <p>Dobrodošli na naš imgur</p>

        <p>
            <a href="{% url 'app:index' %}">Idi na sve slike</a>
        </p>
    </body>
</html>

lab7/myimgur/app/templates/app/index.html
<html>
    <head>
        <title>Naš imgur</title>
    </head>
    <body>
        <p>
            <a href="{% url 'home_path' %}">HOME</a>
        </p>
        <h1>Sve slike</h1>
        <p>Dobrodošli na naš imgur</p>
        {% for image in image_list %}
            <div>
                <p>Naziv: 
                    <a href="{% url 'app:detail' image.id %}">
                        {{ image.title }}
                    </a>
                </p>
                <p>Objavljeno: {{ image.pub_date }}</p>
                <img src="{{ image.url }}" style="width:300px;">
            </div>
        {% endfor %}

        
    </body>
</html>