lab8-prp1/myimgur/app/urls.py
from django.urls import path
from . import views

app_name = "app"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:image_id>', views.detail, name="detail"),
    path('<int:image_id>/comment', views.post_comment, name="post_comment"),
    path('comments/<int:comment_id>/approve', views.approve_comment, name="approve_comment")
]

lab8-prp1/myimgur/myimgur/urls.py
from django.contrib import admin
from django.urls import path, include

from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home_path'),
    path('images/', include('app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

lab8-prp1/myimgur/app/models.py
from django.db import models

# Create your models here.
class Image(models.Model):
    url = models.CharField(max_length=256, blank=False)
    title = models.CharField(max_length=128, blank=False)
    pub_date = models.DateTimeField('Published at')
    def __str__(self):
        return f"{self.id}-{self.title[:20]}"
    
class Comment(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    pub_date = models.DateTimeField('Published at')
    nick = models.CharField(max_length=128, blank=False, default='anon')
    approved = models.BooleanField(default=False) 
    def __str__(self):
        return f"{self.id}-{self.image.title[:15]}-{self.text}"
    

lab8-prp1/myimgur/app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Image, Comment
from django.utils import timezone
from django.urls import reverse

# Create your views here.
def home(request):
    context = {}
    return render(request, 'app/home.html', context)

def index(request):
    images = Image.objects.all()
    context = {
        'image_list': images
    }
    return render(request, 'app/index.html', context)

def detail(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    comments = image.comment_set.all()
    context = {
        'image': image,
        'comments' : comments
    }
    return render(request, 'app/detail.html', context)

def post_comment(request, image_id):
    image = get_object_or_404(Image, pk=image_id)
    comment = Comment(nick= request.POST['nick'], text=request.POST['text'], image = image, pub_date=timezone.now())
    comment.save()
    return HttpResponseRedirect(reverse("app:detail", args=[image_id]))

def approve_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.approved = True
    comment.save()
    return HttpResponseRedirect(reverse('app:detail', args=[comment.image.id]))

lab8-prp1/myimgur/app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>My Lame Imgur</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js" integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}">
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">My Lame Imgur</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'logout' %}">{{user.username}} | Odjava</a>
              </li>
            {% else %}
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'login' %}">Prijava</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">My Lame Imgur</h1>
              <p class="lead">Your one stop place for posting your lamest images!</p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

lab8-prp1/myimgur/app/templates/app/detail.html
{% extends 'app/base.html' %}
{% block content %}

<div class"container">
    <div class="row">
        <div class="col-md-6">
            <h1>{{ image.title }}</h1>
            <div>
                <p>Objavljeno: {{ image.pub_date }}</p>
                <img src="{{ image.url }}" class="full-width">
            </div>
        </div>
        <div class="col-md-6">
            <h1>Komentari</h1> 
            {% for comment in comments %}
                <p class="comment">
                    <strong>{{comment.nick}}</strong>
                    ( {{ comment.pub_date }} ) <br/>
                    {{ comment.text }}
                    {% if not comment.approved %}
                        <br>
                        <span class="red" style="color: red">
                            <form action="{% url 'app:approve_comment' comment.id %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="Approve" >
                            </form>
                        </span>
                    {% endif %}
                </p>
            {% endfor %}
            <form action="{% url 'app:post_comment' image.id %} " method="post">
                {% csrf_token %}
                <p>
                    <label for="comment_nick">Nick</label>
                    <input id="comment_nick" name="nick" type="text">
                </p>

                <p>
                    <label for="comment_text">Text</label>
                    <input id="comment_text" name="text" type="text">
                </p>

                <input type="submit">
            </form>
        </div>     
    </div>
</div>

{% endblock %}

lab8-prp1/myimgur/app/templates/app/home.html
{% extends 'app/base.html' %}
{% block content %}
<h1>MyImgur</h1>
<p>Dobrodošli na naš imgur</p>

<p>
    <a href="{% url 'app:index' %}">Idi na sve slike</a>
</p>
{% endblock content %}

lab8-prp1/myimgur/app/templates/app/index.html
{% extends 'app/base.html' %}
{% block content %}
        <p>
            <a href="{% url 'home_path' %}">HOME</a>
        </p>
        <h1>Sve slike</h1>
        <p>Dobrodošli na naš imgur</p>
        {% for image in image_list %}
            <div>
                <p>Naziv: 
                    <a href="{% url 'app:detail' image.id %}">
                        {{ image.title }}
                    </a>
                </p>
                <p>Objavljeno: {{ image.pub_date }}</p>
                <img src="{{ image.url }}" style="width:300px;">
            </div>
        {% endfor %}
{% endblock content %}